### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by DevEddy** [larsbeck/HomematicIp#6]
When a device is not yet supported is it possible to skip or create a placeholder object?

Reason: The UI and the communication should still work for the known devices. The UI could show the unknown device to the user and he could report that device.

-- Eddy

**Comment by larsbeck** [comment]
Hi Eddy,

I understand and surely that is doable. I'll think about a good way and get back to you asap.

Lars

**Comment by larsbeck** [comment]
Hi Eddy,

I have added a quick work around for unknown devices. They should now deserialize as ExpandoObjects. I haven't had the time to test it, so let me know if you run into any issues.
The upside: You won't get any exceptions due to unknown devices. The downside: You should get an EventNotification for unknown devices as you do for known ones, but for them "HomematicIpObjectBase" will be null.
As a quick fix that is ok, but people will not know why this happened. I'll leave this open until I have the time to come up with a real solution.
